import { s } from "@/lib/redesign/cssString";

export default function Rail() {
  return (
      <nav data-rail aria-label="Section navigation" style={s("position:fixed;right:clamp(14px,2.2vw,32px);top:50%;transform:translateY(-50%);z-index:90;display:flex;flex-direction:column;gap:15px;align-items:flex-end;mix-blend-mode:difference;")}>
          <a href="#top" data-rail-link data-rail-for="top" style={s("text-decoration:none;display:flex;align-items:center;gap:10px;")}><span data-rail-label style={s("opacity:0;transition:opacity .25s ease;font-family:var(--font-mono),ui-monospace,monospace;font-size:10.5px;letter-spacing:0.06em;text-transform:uppercase;color:#fff;white-space:nowrap;")}>Intro</span><span data-rail-tick style={s("display:block;width:14px;height:2px;border-radius:2px;background:#fff;opacity:0.4;transition:width .3s ease,opacity .3s ease;")}></span></a>
          <a href="#case-study" data-rail-link data-rail-for="case-study" style={s("text-decoration:none;display:flex;align-items:center;gap:10px;")}><span data-rail-label style={s("opacity:0;transition:opacity .25s ease;font-family:var(--font-mono),ui-monospace,monospace;font-size:10.5px;letter-spacing:0.06em;text-transform:uppercase;color:#fff;white-space:nowrap;")}>Case study</span><span data-rail-tick style={s("display:block;width:14px;height:2px;border-radius:2px;background:#fff;opacity:0.4;transition:width .3s ease,opacity .3s ease;")}></span></a>
          <a href="#apps" data-rail-link data-rail-for="apps" style={s("text-decoration:none;display:flex;align-items:center;gap:10px;")}><span data-rail-label style={s("opacity:0;transition:opacity .25s ease;font-family:var(--font-mono),ui-monospace,monospace;font-size:10.5px;letter-spacing:0.06em;text-transform:uppercase;color:#fff;white-space:nowrap;")}>Native apps</span><span data-rail-tick style={s("display:block;width:14px;height:2px;border-radius:2px;background:#fff;opacity:0.4;transition:width .3s ease,opacity .3s ease;")}></span></a>
          <a href="#nova" data-rail-link data-rail-for="nova" style={s("text-decoration:none;display:flex;align-items:center;gap:10px;")}><span data-rail-label style={s("opacity:0;transition:opacity .25s ease;font-family:var(--font-mono),ui-monospace,monospace;font-size:10.5px;letter-spacing:0.06em;text-transform:uppercase;color:#fff;white-space:nowrap;")}>N.O.V.A.</span><span data-rail-tick style={s("display:block;width:14px;height:2px;border-radius:2px;background:#fff;opacity:0.4;transition:width .3s ease,opacity .3s ease;")}></span></a>
          <a href="#omi" data-rail-link data-rail-for="omi" style={s("text-decoration:none;display:flex;align-items:center;gap:10px;")}><span data-rail-label style={s("opacity:0;transition:opacity .25s ease;font-family:var(--font-mono),ui-monospace,monospace;font-size:10.5px;letter-spacing:0.06em;text-transform:uppercase;color:#fff;white-space:nowrap;")}>Omi platform</span><span data-rail-tick style={s("display:block;width:14px;height:2px;border-radius:2px;background:#fff;opacity:0.4;transition:width .3s ease,opacity .3s ease;")}></span></a>
          <a href="#stack" data-rail-link data-rail-for="stack" style={s("text-decoration:none;display:flex;align-items:center;gap:10px;")}><span data-rail-label style={s("opacity:0;transition:opacity .25s ease;font-family:var(--font-mono),ui-monospace,monospace;font-size:10.5px;letter-spacing:0.06em;text-transform:uppercase;color:#fff;white-space:nowrap;")}>Stack</span><span data-rail-tick style={s("display:block;width:14px;height:2px;border-radius:2px;background:#fff;opacity:0.4;transition:width .3s ease,opacity .3s ease;")}></span></a>
          <a href="#contact" data-rail-link data-rail-for="contact" style={s("text-decoration:none;display:flex;align-items:center;gap:10px;")}><span data-rail-label style={s("opacity:0;transition:opacity .25s ease;font-family:var(--font-mono),ui-monospace,monospace;font-size:10.5px;letter-spacing:0.06em;text-transform:uppercase;color:#fff;white-space:nowrap;")}>Contact</span><span data-rail-tick style={s("display:block;width:14px;height:2px;border-radius:2px;background:#fff;opacity:0.4;transition:width .3s ease,opacity .3s ease;")}></span></a>
        </nav>
  );
}
